"""
apply_engine/tracking/orm.py
─────────────────────────────
SQLAlchemy ORM models mirroring the Supabase PostgreSQL schema.

Tables modelled here:
    Application            — public.applications
    ApplyRun               — public.apply_runs
    ApplicationEvent       — public.application_events
    ApplicationConfirmation — public.application_confirmations
    ActionRequest          — public.action_requests

Column names and types match the Supabase migrations exactly.
UUID primary keys are generated by PostgreSQL (gen_random_uuid()),
so we declare server_default here and let the DB produce them.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from apply_engine.tracking.db import Base


# ── Helpers ───────────────────────────────────────────────────────────────────

def _utcnow():
    return func.timezone("utc", func.now())


# ── Application ───────────────────────────────────────────────────────────────

class Application(Base):
    __tablename__ = "applications"
    __table_args__ = (
        CheckConstraint(
            "status in ('queued','running','awaiting_confirmation','confirmed',"
            "'cancelled','confirmation_timeout','requires_auth','applied','failed')",
            name="applications_status_check",
        ),
        Index("idx_applications_user_status", "user_id", "status"),
        Index("idx_applications_queue_status", "status", "queued_at", "created_at"),
        Index("idx_applications_request_fingerprint", "user_id", "job_id", "request_fingerprint"),
        {"schema": "public"},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("public.jobs.id", ondelete="CASCADE"), nullable=True
    )

    # ── Status ─────────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(String(64), nullable=False, default="queued")
    execution_status: Mapped[str | None] = mapped_column(String(64), nullable=True)
    latest_user_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Attempt tracking ───────────────────────────────────────────────────
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Request payload (stored for replay) ───────────────────────────────
    request_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    request_fingerprint: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Worker metadata ────────────────────────────────────────────────────
    worker_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    last_run_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("public.apply_runs.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Real-time event stream (legacy JSONB array) ────────────────────────
    log_events: Mapped[list[dict]] = mapped_column(JSONB, nullable=False, default=list)
    preview_screenshot: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Confirmation ───────────────────────────────────────────────────────
    confirmation_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Retry scheduling ───────────────────────────────────────────────────
    retry_after: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Timestamps ────────────────────────────────────────────────────────
    queued_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow(), onupdate=_utcnow()
    )

    # ── Relationships ──────────────────────────────────────────────────────
    events: Mapped[list["ApplicationEvent"]] = relationship(
        back_populates="application",
        order_by="ApplicationEvent.created_at",
        cascade="all, delete-orphan",
    )
    confirmation: Mapped["ApplicationConfirmation | None"] = relationship(
        back_populates="application",
        uselist=False,
        cascade="all, delete-orphan",
    )
    action_requests: Mapped[list["ActionRequest"]] = relationship(
        back_populates="application",
        order_by="ActionRequest.created_at",
        cascade="all, delete-orphan",
    )
    runs: Mapped[list["ApplyRun"]] = relationship(
        back_populates="application",
        foreign_keys="ApplyRun.application_id",
        order_by="ApplyRun.created_at",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Application id={self.id} status={self.status}>"


# ── ApplyRun ──────────────────────────────────────────────────────────────────

class ApplyRun(Base):
    __tablename__ = "apply_runs"
    __table_args__ = (
        Index("idx_apply_runs_user_created_at", "user_id", "created_at"),
        Index("idx_apply_runs_mode_status", "mode", "status", "created_at"),
        Index("idx_apply_runs_application_id", "application_id", "created_at"),
        {"schema": "public"},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("public.jobs.id", ondelete="SET NULL"), nullable=True
    )
    application_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("public.applications.id", ondelete="SET NULL"),
        nullable=True,
    )
    mode: Mapped[str] = mapped_column(String(16), nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    portal: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    request_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    result_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )

    application: Mapped["Application | None"] = relationship(
        back_populates="runs",
        foreign_keys=[application_id],
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<ApplyRun id={self.id} mode={self.mode} status={self.status}>"


# ── ApplicationEvent ──────────────────────────────────────────────────────────

class ApplicationEvent(Base):
    """Structured, append-only event log for an application run."""

    __tablename__ = "application_events"
    __table_args__ = (
        Index("idx_application_events_app_created", "application_id", "created_at"),
        Index("idx_application_events_user_type", "user_id", "event_type", "created_at"),
        {"schema": "public"},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    application_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("public.applications.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    attempt_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    level: Mapped[str] = mapped_column(String(16), nullable=False, default="info")
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")
    data: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )

    application: Mapped["Application"] = relationship(back_populates="events")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<ApplicationEvent type={self.event_type} level={self.level}>"


# ── ApplicationConfirmation ───────────────────────────────────────────────────

class ApplicationConfirmation(Base):
    """Structured evidence record for a successful submission."""

    __tablename__ = "application_confirmations"
    __table_args__ = (
        UniqueConstraint("application_id", name="uq_application_confirmations_application_id"),
        Index("idx_application_confirmations_user", "user_id", "detected_at"),
        {"schema": "public"},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    application_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("public.applications.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    attempt_number: Mapped[int] = mapped_column(Integer, nullable=False)
    confirmation_type: Mapped[str] = mapped_column(String(32), nullable=False)
    detected_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    external_application_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence_screenshot_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )

    application: Mapped["Application"] = relationship(back_populates="confirmation")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<ApplicationConfirmation type={self.confirmation_type} score={self.confidence_score}>"


# ── ActionRequest ─────────────────────────────────────────────────────────────

class ActionRequest(Base):
    """A request for human input raised mid-run by the automation engine."""

    __tablename__ = "action_requests"
    __table_args__ = (
        Index("idx_action_requests_app_status", "application_id", "status", "created_at"),
        Index("idx_action_requests_user_pending", "user_id", "status", "expires_at"),
        {"schema": "public"},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    application_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("public.applications.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    attempt_number: Mapped[int] = mapped_column(Integer, nullable=False)
    action_type: Mapped[str] = mapped_column(String(16), nullable=False)
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    context: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="pending")
    response: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_utcnow()
    )
    responded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    application: Mapped["Application"] = relationship(back_populates="action_requests")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<ActionRequest type={self.action_type} status={self.status}>"
