export const SCHOOLS: string[] = [
  "American University",
  "Arizona State University",
  "Auburn University",
  "Australian National University",
  "Baylor University",
  "Boston College",
  "Boston University",
  "Brigham Young University",
  "Brown University",
  "Cal Poly San Luis Obispo",
  "California Institute of Technology",
  "Cambridge University",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Colorado State University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Drexel University",
  "Duke University",
  "Emory University",
  "ETH Zurich",
  "Florida State University",
  "Georgetown University",
  "George Washington University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Harvey Mudd College",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "Imperial College London",
  "Indiana University",
  "Johns Hopkins University",
  "KAIST",
  "Lehigh University",
  "Louisiana State University",
  "Massachusetts Institute of Technology",
  "McGill University",
  "Miami University",
  "Nanyang Technological University",
  "National University of Singapore",
  "New York University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Oklahoma State University",
  "Oregon State University",
  "Oxford University",
  "Peking University",
  "Penn State University",
  "Princeton University",
  "Purdue University",
  "Rensselaer Polytechnic Institute",
  "Rice University",
  "Rose-Hulman Institute of Technology",
  "Rutgers University",
  "San Jose State University",
  "Santa Clara University",
  "Seoul National University",
  "SMU (Southern Methodist University)",
  "Stanford University",
  "Stevens Institute of Technology",
  "SUNY Stony Brook",
  "Temple University",
  "Texas A&M University",
  "Tsinghua University",
  "Tufts University",
  "Tulane University",
  "UC Berkeley",
  "UC Davis",
  "UC Irvine",
  "UC Santa Barbara",
  "UC Santa Cruz",
  "UCLA",
  "UCSD",
  "University at Buffalo",
  "University of Alabama",
  "University of Arizona",
  "University of British Columbia",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Edinburgh",
  "University of Florida",
  "University of Georgia",
  "University of Houston",
  "University of Illinois Urbana-Champaign",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Melbourne",
  "University of Memphis",
  "University of Michigan",
  "University of Minnesota",
  "University of Missouri",
  "University of Nebraska",
  "University of New Mexico",
  "University of North Carolina Chapel Hill",
  "University of Notre Dame",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of San Francisco",
  "University of South Carolina",
  "University of Southern California",
  "University of Sydney",
  "University of Tennessee",
  "University of Texas at Austin",
  "University of Toronto",
  "University of Utah",
  "University of Virginia",
  "University of Washington",
  "University of Waterloo",
  "University of Wisconsin-Madison",
  "UNSW Sydney",
  "UT Dallas",
  "Vanderbilt University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Worcester Polytechnic Institute",
  "Yale University",
];
