export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      applications: {
        Row: {
          applied_at: string | null;
          attempt_count: number;
          browsing_task_id: string | null;
          completed_at: string | null;
          confirmation_text: string | null;
          created_at: string;
          id: string;
          job_id: string;
          last_error: string | null;
          last_run_id: string | null;
          queued_at: string;
          request_fingerprint: string | null;
          request_payload: Json;
          started_at: string | null;
          status: string;
          updated_at: string;
          user_id: string;
          worker_id: string | null;
        };
        Insert: {
          applied_at?: string | null;
          attempt_count?: number;
          browsing_task_id?: string | null;
          completed_at?: string | null;
          confirmation_text?: string | null;
          created_at?: string;
          id?: string;
          job_id: string;
          last_error?: string | null;
          last_run_id?: string | null;
          queued_at?: string;
          request_fingerprint?: string | null;
          request_payload?: Json;
          started_at?: string | null;
          status?: string;
          updated_at?: string;
          user_id: string;
          worker_id?: string | null;
        };
        Update: {
          applied_at?: string | null;
          attempt_count?: number;
          browsing_task_id?: string | null;
          completed_at?: string | null;
          confirmation_text?: string | null;
          created_at?: string;
          id?: string;
          job_id?: string;
          last_error?: string | null;
          last_run_id?: string | null;
          queued_at?: string;
          request_fingerprint?: string | null;
          request_payload?: Json;
          started_at?: string | null;
          status?: string;
          updated_at?: string;
          user_id?: string;
          worker_id?: string | null;
        };
        Relationships: [];
      };
      apply_runs: {
        Row: {
          created_at: string;
          error: string | null;
          id: string;
          job_id: string | null;
          mode: string;
          portal: string | null;
          request_payload: Json;
          result_payload: Json;
          status: string;
          url: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          error?: string | null;
          id?: string;
          job_id?: string | null;
          mode: string;
          portal?: string | null;
          request_payload?: Json;
          result_payload?: Json;
          status: string;
          url: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          error?: string | null;
          id?: string;
          job_id?: string | null;
          mode?: string;
          portal?: string | null;
          request_payload?: Json;
          result_payload?: Json;
          status?: string;
          url?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      alerts: {
        Row: {
          alerted_at: string;
          expires_at: string | null;
          id: string;
          job_id: string;
          metadata: Json;
          replied_at: string | null;
          response_channel: string | null;
          status: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          alerted_at?: string;
          expires_at?: string | null;
          id?: string;
          job_id: string;
          metadata?: Json;
          replied_at?: string | null;
          response_channel?: string | null;
          status?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          alerted_at?: string;
          expires_at?: string | null;
          id?: string;
          job_id?: string;
          metadata?: Json;
          replied_at?: string | null;
          response_channel?: string | null;
          status?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          application_url: string;
          canonical_application_url: string | null;
          canonical_url: string | null;
          company: string;
          created_at: string;
          experience_band: string | null;
          external_job_key: string | null;
          id: string;
          industries: string[];
          is_early_career: boolean;
          jd_summary: string | null;
          job_career_node_ids: string[];
          job_degree_requirement_node_ids: string[];
          job_employment_type_node_ids: string[];
          job_education_field_node_ids: string[];
          job_function_node_ids: string[];
          job_geo_node_ids: string[];
          job_industry_node_ids: string[];
          job_taxonomy_summary: Json;
          job_work_auth_node_ids: string[];
          level: string;
          location: string;
          locations_text: string[];
          metadata: Json;
          portal: string | null;
          posted_at: string;
          remote: boolean;
          role_family: string | null;
          scraped_at: string;
          status: string;
          target_term: string | null;
          target_year: number | null;
          taxonomy_needs_review: boolean;
          taxonomy_resolution_version: string | null;
          title: string;
          updated_at: string;
          url: string;
          work_modality: string | null;
          work_modality_confidence: string | null;
        };
        Insert: {
          application_url: string;
          canonical_application_url?: string | null;
          canonical_url?: string | null;
          company: string;
          created_at?: string;
          experience_band?: string | null;
          external_job_key?: string | null;
          id?: string;
          industries?: string[];
          is_early_career?: boolean;
          jd_summary?: string | null;
          job_career_node_ids?: string[];
          job_degree_requirement_node_ids?: string[];
          job_employment_type_node_ids?: string[];
          job_education_field_node_ids?: string[];
          job_function_node_ids?: string[];
          job_geo_node_ids?: string[];
          job_industry_node_ids?: string[];
          job_taxonomy_summary?: Json;
          job_work_auth_node_ids?: string[];
          level: string;
          location: string;
          locations_text?: string[];
          metadata?: Json;
          portal?: string | null;
          posted_at: string;
          remote?: boolean;
          role_family?: string | null;
          scraped_at?: string;
          status?: string;
          target_term?: string | null;
          target_year?: number | null;
          taxonomy_needs_review?: boolean;
          taxonomy_resolution_version?: string | null;
          title: string;
          updated_at?: string;
          url: string;
          work_modality?: string | null;
          work_modality_confidence?: string | null;
        };
        Update: {
          application_url?: string;
          canonical_application_url?: string | null;
          canonical_url?: string | null;
          company?: string;
          created_at?: string;
          experience_band?: string | null;
          external_job_key?: string | null;
          id?: string;
          industries?: string[];
          is_early_career?: boolean;
          jd_summary?: string | null;
          job_career_node_ids?: string[];
          job_degree_requirement_node_ids?: string[];
          job_employment_type_node_ids?: string[];
          job_education_field_node_ids?: string[];
          job_function_node_ids?: string[];
          job_geo_node_ids?: string[];
          job_industry_node_ids?: string[];
          job_taxonomy_summary?: Json;
          job_work_auth_node_ids?: string[];
          level?: string;
          location?: string;
          locations_text?: string[];
          metadata?: Json;
          portal?: string | null;
          posted_at?: string;
          remote?: boolean;
          role_family?: string | null;
          scraped_at?: string;
          status?: string;
          target_term?: string | null;
          target_year?: number | null;
          taxonomy_needs_review?: boolean;
          taxonomy_resolution_version?: string | null;
          title?: string;
          updated_at?: string;
          url?: string;
          work_modality?: string | null;
          work_modality_confidence?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          authorized_to_work: boolean;
          city: string | null;
          country: string;
          created_at: string;
          cover_letter_template: string | null;
          daily_digest_cutoff_time_local: string;
          daily_digest_enabled: boolean;
          daily_digest_goal_submit_time_local: string;
          daily_digest_shortlist_time_local: string;
          daily_digest_time_local: string;
          daily_digest_timezone: string;
          daily_review_window_minutes: number;
          degree: string | null;
          earliest_start_date: string | null;
          eeo: Json | null;
          email: string | null;
          full_name: string | null;
          github_url: string | null;
          gpa: string | null;
          graduation: string | null;
          graduation_term: string | null;
          graduation_year: number | null;
          gray_areas: Json | null;
          id: string;
          industries: string[];
          levels: string[];
          linkedin_url: string | null;
          locations: string[];
          major2: string | null;
          major: string | null;
          notification_pref: string;
          onboarding_completed: boolean;
          phone: string | null;
          profile_application_facts: Json;
          profile_career_allow_node_ids: string[];
          profile_degree_node_ids: string[];
          profile_education_field_node_ids: string[];
          profile_employment_type_allow_node_ids: string[];
          profile_geo_allow_node_ids: string[];
          profile_industry_allow_node_ids: string[];
          profile_job_function_allow_node_ids: string[];
          profile_match_preferences: Json;
          profile_taxonomy_summary: Json;
          profile_work_auth_node_ids: string[];
          profile_work_modality_allow: string[];
          remote_ok: boolean;
          resume_json: Json | null;
          resume_url: string | null;
          school: string | null;
          sms_opt_in: boolean;
          sms_provider: string | null;
          state_region: string | null;
          subscription_tier: string;
          target_role_families: string[];
          target_terms: string[];
          target_years: number[];
          updated_at: string;
          visa_type: string | null;
          weekly_availability_hours: string | null;
          website_url: string | null;
        };
        Insert: {
          authorized_to_work?: boolean;
          city?: string | null;
          country?: string;
          created_at?: string;
          cover_letter_template?: string | null;
          daily_digest_cutoff_time_local?: string;
          daily_digest_enabled?: boolean;
          daily_digest_goal_submit_time_local?: string;
          daily_digest_shortlist_time_local?: string;
          daily_digest_time_local?: string;
          daily_digest_timezone?: string;
          daily_review_window_minutes?: number;
          degree?: string | null;
          earliest_start_date?: string | null;
          eeo?: Json | null;
          email?: string | null;
          full_name?: string | null;
          github_url?: string | null;
          gpa?: string | null;
          graduation?: string | null;
          graduation_term?: string | null;
          graduation_year?: number | null;
          gray_areas?: Json | null;
          id: string;
          industries?: string[];
          levels?: string[];
          linkedin_url?: string | null;
          locations?: string[];
          major2?: string | null;
          major?: string | null;
          notification_pref?: string;
          onboarding_completed?: boolean;
          phone?: string | null;
          profile_application_facts?: Json;
          profile_career_allow_node_ids?: string[];
          profile_degree_node_ids?: string[];
          profile_education_field_node_ids?: string[];
          profile_employment_type_allow_node_ids?: string[];
          profile_geo_allow_node_ids?: string[];
          profile_industry_allow_node_ids?: string[];
          profile_job_function_allow_node_ids?: string[];
          profile_match_preferences?: Json;
          profile_taxonomy_summary?: Json;
          profile_work_auth_node_ids?: string[];
          profile_work_modality_allow?: string[];
          remote_ok?: boolean;
          resume_json?: Json | null;
          resume_url?: string | null;
          school?: string | null;
          sms_opt_in?: boolean;
          sms_provider?: string | null;
          state_region?: string | null;
          subscription_tier?: string;
          target_role_families?: string[];
          target_terms?: string[];
          target_years?: number[];
          updated_at?: string;
          visa_type?: string | null;
          weekly_availability_hours?: string | null;
          website_url?: string | null;
        };
        Update: {
          authorized_to_work?: boolean;
          city?: string | null;
          country?: string;
          created_at?: string;
          cover_letter_template?: string | null;
          daily_digest_cutoff_time_local?: string;
          daily_digest_enabled?: boolean;
          daily_digest_goal_submit_time_local?: string;
          daily_digest_shortlist_time_local?: string;
          daily_digest_time_local?: string;
          daily_digest_timezone?: string;
          daily_review_window_minutes?: number;
          degree?: string | null;
          earliest_start_date?: string | null;
          eeo?: Json | null;
          email?: string | null;
          full_name?: string | null;
          github_url?: string | null;
          gpa?: string | null;
          graduation?: string | null;
          graduation_term?: string | null;
          graduation_year?: number | null;
          gray_areas?: Json | null;
          id?: string;
          industries?: string[];
          levels?: string[];
          linkedin_url?: string | null;
          locations?: string[];
          major2?: string | null;
          major?: string | null;
          notification_pref?: string;
          onboarding_completed?: boolean;
          phone?: string | null;
          profile_application_facts?: Json;
          profile_career_allow_node_ids?: string[];
          profile_degree_node_ids?: string[];
          profile_education_field_node_ids?: string[];
          profile_employment_type_allow_node_ids?: string[];
          profile_geo_allow_node_ids?: string[];
          profile_industry_allow_node_ids?: string[];
          profile_job_function_allow_node_ids?: string[];
          profile_match_preferences?: Json;
          profile_taxonomy_summary?: Json;
          profile_work_auth_node_ids?: string[];
          profile_work_modality_allow?: string[];
          remote_ok?: boolean;
          resume_json?: Json | null;
          resume_url?: string | null;
          school?: string | null;
          sms_opt_in?: boolean;
          sms_provider?: string | null;
          state_region?: string | null;
          subscription_tier?: string;
          target_role_families?: string[];
          target_terms?: string[];
          target_years?: number[];
          updated_at?: string;
          visa_type?: string | null;
          weekly_availability_hours?: string | null;
          website_url?: string | null;
        };
        Relationships: [];
      };
      request_rate_limits: {
        Row: {
          hit_count: number;
          scope: string;
          subject: string;
          updated_at: string;
          window_started_at: string;
        };
        Insert: {
          hit_count?: number;
          scope: string;
          subject: string;
          updated_at?: string;
          window_started_at: string;
        };
        Update: {
          hit_count?: number;
          scope?: string;
          subject?: string;
          updated_at?: string;
          window_started_at?: string;
        };
        Relationships: [];
      };
      taxonomy_nodes: {
        Row: {
          created_at: string;
          depth: number;
          dimension: string;
          id: string;
          is_leaf: boolean;
          label: string;
          metadata: Json;
          parent_node_id: string | null;
          slug: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          depth?: number;
          dimension: string;
          id?: string;
          is_leaf?: boolean;
          label: string;
          metadata?: Json;
          parent_node_id?: string | null;
          slug: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          depth?: number;
          dimension?: string;
          id?: string;
          is_leaf?: boolean;
          label?: string;
          metadata?: Json;
          parent_node_id?: string | null;
          slug?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      consume_rate_limit: {
        Args: {
          p_limit: number;
          p_scope: string;
          p_subject: string;
          p_window_seconds: number;
        };
        Returns: {
          allowed: boolean;
          remaining: number;
          reset_at: string;
        }[];
      };
      claim_next_application: {
        Args: {
          p_user_id?: string | null;
          p_worker_id: string;
        };
        Returns: Database["public"]["Tables"]["applications"]["Row"][];
      };
      select_candidate_jobs_for_profile: {
        Args: {
          p_profile_id: string;
          p_since?: string | null;
        };
        Returns: Database["public"]["Tables"]["jobs"]["Row"][];
      };
      select_candidate_profiles_for_job: {
        Args: {
          p_industries: string[];
          p_location: string;
          p_remote: boolean;
          p_role_family: string;
          p_target_term: string | null;
          p_target_year: number | null;
        };
        Returns: {
          id: string;
        }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
